require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - vagrant/**/*
    - script/*_temp.rb

Rails:
  Enabled: true

Rails/SkipsModelValidations:
  Exclude:
    - 'test/**/*.rb'

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - lib/tasks/*
    - lib/tasks/*/*
    - app/*/concerns/*.rb
    - app/views/*/*.xml.builder
    - app/views/*/*.json.jbuilder
    - app/views/*/*/*.xml.builder
    - app/admin/*
    - app/views/admin/*/*.html.arb

Lint/ScriptPermission:
  Exclude:
    - script/*

Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/EmptyCaseCondition:
  Description: 'Avoid empty condition in case statements.'
  Enabled: false
