source 'https://rubygems.org'
source 'http://oh-stage-utility-1.blackducksoftware.com:9292/'

gem 'activeadmin', github: 'activeadmin'
gem 'aws-sdk'
gem 'brakeman'
gem 'coffee-rails'
gem 'coffee-script-source', '~>1.8.0'
gem 'dotenv-rails'
gem 'haml-rails'
gem 'jbuilder'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'mini_magick', '~> 4.1.1'
gem 'oh_delegator'
gem 'ohno-you-dont', require: 'ohno'
gem 'paperclip'
gem 'pg'
gem 'rails'
gem 'rubocop'
gem 'recaptcha', github: 'ambethia/recaptcha'
gem 'sass-rails'
gem 'squeel'
gem 'therubyracer'
gem 'turbolinks'
gem 'twitter-bootstrap-rails'
gem 'uglifier'
gem 'will_paginate'
gem 'will_paginate-bootstrap'

group :development, :vagrant do
  gem 'capistrano-rails'
  gem 'capistrano-passenger'
  gem 'letter_opener'
  gem 'pry-rails'
end

group :test do
  gem 'byebug'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'flog'
  gem 'haml-lint', '~> 0.11'
  gem 'minitest-rails'
  gem 'mocha'
  gem 'pry-rails'
  gem 'ruby_parser'
  gem 'simplecov'
  gem 'simplecov-rcov'
  gem 'spring'
  gem 'vcr'
  gem 'webmock'
end
