source 'https://rubygems.org'

gem 'brakeman'
gem 'coffee-rails'
gem 'haml-rails'
gem 'jbuilder'
gem 'jquery-rails'
gem 'pg'
gem 'rails'
gem 'rubocop'
gem 'sass-rails'
gem 'therubyracer'
gem 'turbolinks'
gem 'twitter-bootstrap-rails'
gem 'uglifier'
gem 'will_paginate'
gem 'dotenv-rails'
gem 'paperclip'
gem 'aws-sdk'
gem 'squeel'
gem 'draper'
gem 'oh_delegator', git: 'git@github.com:blackducksw/oh_delegator.git'

group :development, :test, :vagrant do
  gem 'byebug'
  gem 'factory_girl_rails'
  gem 'flog'
  gem 'haml-lint'
  gem 'minitest-rails'
  gem 'mocha'
  gem 'simplecov'
  gem 'simplecov-rcov'
  gem 'spring'
  gem 'faker'
  gem 'letter_opener'
  gem 'pry-rails'
end
