source 'https://rubygems.org'

gem 'activeadmin', '1.0.0'
gem 'airbrake', '~> 5.5'
gem 'aws-sdk', '< 2.0' # paperclip doesn't work with the new aws-sdk gem
gem 'redcarpet'
gem 'brakeman'
gem 'bundler-audit'
gem 'clearance'
gem 'coffee-rails'
gem 'coffee-script-source', '~>1.8.0'
gem 'doorkeeper'
gem 'dotenv-rails'
gem 'execjs'
gem 'font-awesome-rails'
gem 'haml-rails', '~> 1.0'
gem 'jbuilder'
gem 'jquery-rails', '~> 4.2.1'
gem 'jquery-ui-rails', '~> 5.0.5'
gem 'mini_magick', '~> 4.1.1'
gem 'nokogiri', '~> 1.8.1'
gem 'newrelic_rpm'
gem 'oh_delegator'
gem 'ohloh_scm', '2.4.0'
gem 'open4'
gem 'paperclip', '< 5.0 '
gem 'pg'
gem 'rails', '~> 4.2.7.1'
gem 'rails-html-sanitizer'
gem 'recaptcha', require: 'recaptcha/rails'
gem 'redis-rails', '>= 5.0.2'
gem 'rubocop', '~> 0.40.0', require: false
gem 'sass-rails'
gem 'therubyracer'
gem 'thor'
gem 'twitter-bootstrap-rails'
gem 'uglifier', '>= 2.7.2'
gem 'will_paginate'
gem 'will_paginate-bootstrap'
gem 'sprockets-rails', '~> 2.3.3'
gem 'feedjira'
gem 'whenever', require: false
gem 'sidekiq'
gem 'secondbase'
gem 'simplemde-rails'
gem 'jwt'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller', '~> 0.7.2'
  gem 'capistrano'
  gem 'capistrano-faster-assets'
  gem 'capistrano-rails'
  gem 'capistrano-passenger'
  gem 'capistrano-sidekiq'
  gem 'capistrano-rbenv', '~> 2.0'
  gem 'guard'
  gem 'guard-rubocop'
  gem 'guard-haml_lint'
  gem 'guard-coffeescript'
  gem 'guard-livereload', '~> 2.5', '>= 2.5.2', require: false
  gem 'meta_request'
  gem 'quiet_assets'
end

group :test do
  gem 'flog'
  gem 'haml_lint'
  gem 'minitest-rails'
  gem 'm', '~> 1.5.0'
  gem 'mocha'
  gem 'ruby_parser'
  gem 'simplecov'
  gem 'simplecov-rcov'
  gem 'spring'
  gem 'timecop'
  gem 'vcr'
  gem 'webmock'
end

group :development, :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'byebug'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'rb-readline'
  gem 'rails-erd'
  gem 'jasmine-rails'
  gem 'jasmine-jquery-rails'
  gem 'selenium-webdriver'
  gem 'spinach'
  gem 'spinach-console-reporter'
  gem 'teaspoon-jasmine'
end

group :production do
end

group :development, :staging do
  gem 'letter_opener'
  gem 'letter_opener_web', '~> 1.2.0'
end
