#! /usr/bin/env ruby

raise 'RAILS_ENV is undefined' unless ENV['RAILS_ENV']

require_relative '../config/environment'

class SetCodeLocationStatus
  def execute
   conn = ActiveRecord::Base.connection
   conn.execute("CREATE temp table kbLocations 
        (id integer);")
        
   rc = conn.raw_connection
   rc.exec("COPY kbLocations (id) FROM STDIN WITH CSV")
 
   file = File.open('tmp/oh-code-locations.csv', 'r')
   while !file.eof?
     # Add row to copy data
     rc.put_copy_data(file.readline)
    end
 
    # We are done adding copy data
    rc.put_copy_end
  
  
  end
end