highstock: true
chart:
  defaultSeriesType: 'line'
plotOptions:
  series:
    cursor: 'arrow'
    dataGrouping:
      enabled: false
  type: {}
yAxis:
  min: 0
  endOnTick: false
  showLastLabel: true
  maxPadding: 0.25
xAxis:
  dateTimeLabelFormats:
    millisecond: '%Y'
    tickInterval: 31557600000.0
    minPadding: 0.015
    maxPadding: 0.015
tooltip:
  xDateFormat: '%B %Y'
  headerFormat: '{point.key}<br/>'
  shared: true
  split: false
  style:
    padding: '12px'
navigator:
  series:
    type: 'area'
  xAxis:
    dateTimeLabelFormats:
      millisecond: '%Y'
  yAxis:
    min: 0
  dataGrouping:
    enabled: false
credits:
    enabled: false
exporting:
  enabled: false
