chart:
  backgroundColor: transparent
plotOptions:
  series:
    pointWidth:
    minPointLength: 3
yAxis:
  showFirstLabel: false
xAxis:
  labels:
    align: left
  labels:
    rotation: 0
    step: 1
colors: ['#2f7ed8']
legend:
  enabled: false
