chart:
  type: 'pie'
  renderTo: 'demographics_chart'
  plotShadow: false
  styledMode: true
title:
  text:
  align: 'right'
  y: 60
  floating: 'true'
  style:
    color: '#000'
    fontSize: '10pt'
tooltip:
  formatter: ''
  style:
    fontSize: '11pt'
    padding: '8px'
plotOptions:
  pie:
    allowPointSelect: true
    cursor: 'pointer'
    showInLegend: true
    innerSize: '55%'
    slicedOffset: 0
    borderWidth: 2
    dataLabels:
      enabled: true
      minSize: 1
      color: '#000000'
      connectorColor: '#94a3b8'
      format: '{point.name}: {point.y}%'
legend:
  enabled: true
  align: 'center'
  verticalAlign: 'bottom'
  layout: 'horizontal'
  symbolRadius: 6
  symbolHeight: 12
  symbolWidth: 12
  labelFormat: '{name} ({y}%)'
  itemStyle:
    fontWeight: 'normal'
    fontSize: '12px'
credits:
  enabled: false
series: [{type: 'pie'}]
exporting:
  enabled: false
