#! /usr/bin/env ruby

require_relative '../config/environment'

module ProjectUrlNameFixer
  module_function

  def perform
    Project.where("url_name like '%.%'").each do |project|
      new_url_name = project.url_name.gsub(/[^\w_-]/, '-')
      project.update!(url_name: new_url_name, editor_account: Account.hamster)
    end
  end
end

ProjectUrlNameFixer.perform
