#! /usr/bin/env ruby

require_relative '../config/environment'

module ProjectUserCountFixer
  module_function

  def execute
    projects = Project.select('DISTINCT(projects.id)').joins(stacks: :account).where('accounts.level < 0')
    projects.each { |project| project.update_column(:user_count, project.stacks_count) }
  end
end

ProjectUserCountFixer.execute
