#! /usr/bin/env ruby

require_relative '../config/environment'

# cleanup repositories which has both branch_name and module_name
ActiveRecord::Base.connection.execute("
  UPDATE repositories set module_name = 'default' where coalesce(module_name, '') = ''
    and type = 'HgRepository';
")

ActiveRecord::Base.connection.execute("
  UPDATE repositories set module_name = 'trunk' where coalesce(module_name, '') = ''
    and type in ('BzrRepository', 'SvnRepository', 'SvnSyncRepository');
")

# populate code_locations from repositories
ActiveRecord::Base.connection.execute("
  insert into code_locations(repository_id, module_branch_name,
    created_at, updated_at)
    select id, module_name, created_at, updated_at
    from repositories where
    type != 'GitRepository'
")

ActiveRecord::Base.connection.execute("
  insert into code_locations(repository_id, module_branch_name,
    created_at, updated_at)
    select id, branch_name, created_at, updated_at
    from repositories where
    type = 'GitRepository'
")

# update code_locations status
ActiveRecord::Base.connection.execute("
  update code_locations set status = 2
  from enlistments
  where deleted and enlistments.repository_id = code_locations.repository_id
")

# Fill code_location ids in reference tables

ActiveRecord::Base.connection.execute("
  update enlistments E set code_location_id = C.id from code_locations C where C.repository_id = E.repository_id
")
