#! /usr/bin/env ruby

fail 'RAILS_ENV is undefined' unless ENV['RAILS_ENV']

require_relative '../config/environment'

puts PropertyEdit.where(target_type: 'Organization').for_property('url_name').update_all(key: 'vanity_url')
