#! /usr/bin/env ruby

raise 'RAILS_ENV is undefined' unless ENV['RAILS_ENV']

require_relative '../config/environment'

# rubocop:disable Rails/SkipsModelValidations # We want a quick DB update here.
RssFeed.where(id: RssSubscription.not_deleted.select('rss_feed_id'))
       .where("(next_fetch >= NOW() AT TIME ZONE 'UTC') AND error IS NOT NULL")
       .update_all(next_fetch: Time.current - 1.day)
